organization: # Name of your organization (mandatory)
  name: "ProjectX"

database: # Database credentials, must match what you have in the docker-compose (mandatory)
  host: "postgresql"
  port: 5432
  name: "conduktor-console"
  username: "testuser"
  password: "password"

admin: # Define the local admin for the initial setup (mandatory)
  email: admin@test.com
  password: TeStUsEr1!

auth: # Define a local user (optional)
  local-users:
    - email: user@test.com
      password: TeStUsEr2!

monitoring: # Monitoring settings (optional)
  cortex-url: http://conduktor-monitoring:9009/
  alert-manager-url: http://conduktor-monitoring:9010/
  callback-url: http://conduktor-console:8080/monitoring/api/
  notifications-callback-url: http://localhost:8080

clusters: # Cluster and schema registry configuration (optional)
  - id: my-local-kafka-cluster
    name: My Local Kafka Cluster
    bootstrapServers: "kafka:19092"
    schemaRegistry:
      url: "http://schema-registry:8081"
