server:
  port: 8091

spring:
  application:
    name: consumer

  datasource:
    url: jdbc:h2:mem:wikimedia
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2

  kafka:
    consumer:
      auto-offset-reset: earliest