CREATE TABLE wikimedia_record (
                                  wikimedia_record_id BIGSERIAL PRIMARY KEY,
                                  id BIGINT,
                                  type VARCHAR(255),
                                  title VARCHAR(255),
                                  title_url VARCHAR(255),
                                  comment TEXT,
                                  timestamp BIGINT,
                                  "user" VARCHAR(255),
                                  bot BOOLEAN,
                                  notify_url VARCHAR(255),
                                  minor BOOLEAN,
                                  patrolled BOOLEAN,
                                  server_url VARCHAR(255),
                                  server_name VARCHAR(255),
                                  server_script_path VARCHAR(255),
                                  wiki VARCHAR(255),
                                  parsedcomment TEXT,
                                  meta_id VARCHAR(255),
                                  namespace INT DEFAULT 0,
                                  meta_uri VARCHAR(255) DEFAULT '',
                                  meta_partition INT DEFAULT 0,
                                  meta_offset BIGINT DEFAULT 0,
                                  meta_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                  meta_domain VARCHAR(255) DEFAULT '',
                                  meta_stream VARCHAR(255) DEFAULT '',
                                  meta_topic VARCHAR(255) DEFAULT 'default_value',
                                  meta_dt VARCHAR(255) DEFAULT ''
);


