server:
  port: 8090

spring:
  application:
    name: producer

  kafka:
    bootstrap-servers: http://localhost:9092
    schema-registry-url: http://localhost:8081
    request-timeout-ms: 3000
    max-block-ms: 3000